# -*- coding: utf-8 -*-
"""Presentation copy in both languages."""

COPY = {
 'en': dict(
  lang='en', title='The Right Name On It', other='da', otherLabel='Dansk', selfLabel='English',
  badge='Capability-matched work distribution',
  heroTitle='Work goes in a folder. The right name comes out.',
  heroBody='A head of distribution drops a job into a folder and stops thinking about it. The system checks it against what every person on the team can actually do — recorded levels, certifications and their expiry dates, availability, workload — removes everyone who does not qualify, ranks the ones who do, and hands the work over with its reasoning attached.',
  chip1='Nobody unqualified is ever in the running',
  chip2='Every decision explains itself',
  chip3='Finished work stays attached to a person',
  pipeEyebrow='What happens to one task', pipeTitle='Four steps, in this order, every time',
  pipeBody='The order matters. Qualification is settled before ranking begins, so no score can ever talk the system into someone who should not be there.',
  step='STEP',
  s1t='The admin fills in the job', s1b='What the work is, how long it should take, when it is due, and which capabilities it needs. That is the last decision a person has to make.',
  s2t='Unqualified people are removed', s2b='Missing capability, level too low, expired certification, wrong language, on leave, no capacity left. Fail one and you are out — there is no score in this step.',
  s3t='The rest are ranked', s3b='Seven weighted factors: how far each person clears the bar, whether a lead verified it, experience, spare capacity, workload balance, the deadline, and role fit.',
  s4t='One person gets it — on the record', s4b='The assignment carries its own reasoning. Everyone who was passed over is listed with the exact requirement they missed.',
  teamEyebrow='The team', teamTitle='Five people, five different educations',
  teamBody1='This is what the system reads. Not a job title — a specification: what each person studied, what they are genuinely good at and to what level, which certificates they hold and when those run out, and every job they have finished.',
  teamBody2a='A capability marked', teamBody2b='has been signed off by a lead. One that is only self-declared still counts, but it ranks below a verified one.',
  hEducation='EDUCATION', hGoodAt='WHAT THEY ARE GOOD AT', hCompleted='WORK THEY HAVE COMPLETED', thesisWord='Thesis:',
  d1Eyebrow='Decision one — the gate does the work', d1Title='An emergency callout on a live site',
  d1Body1='A packing line keeps tripping. The site is live, so the job needs someone who can find an electrical fault <em>and</em> holds a current low-voltage work permit. The admin types it once and sends it to the folder.',
  d1Body2='Four of the five are removed — and for four <em>different</em> reasons. Watch Freja in particular.',
  d1NoteTitle='This is the moment worth pausing on.',
  d1NoteBody='Freja is an electrician. She has fault-finding at level 4, verified, and the best customer-handover score on the team. A human scanning a list of names would have sent her. Her permit lapsed twenty-one days ago, so the system would not — and it says so in one line instead of letting her arrive on a live site without it.',
  d2Eyebrow='Decision two — the ranking does the work', d2Title='A quarterly report, same five people',
  d2Body1='Now the folder gets something completely different: a reliability report that needs technical writing, and ideally data analysis. Four people qualify, so the gate steps back and the ranking decides.',
  d2Body2='<strong>And Freja is back in the running.</strong> Her lapsed permit had nothing to do with writing a report, so it never enters the calculation. The system judges each task on its own requirements — it does not carry a grudge from one job to the next.',
  d2NoteTitle='Jonas wins on merit, not seniority.',
  d2NoteBody='He is the newest and least-assigned person on the team. He takes this one because he clears both capabilities with room to spare, both are lead-verified, and he is carrying the lightest workload — not because anyone remembered his name.',
  reqTitle='What this task requires', shortTitle='Ranked shortlist', blockTitle='Not considered — and exactly why', blockTitle2='Not considered',
  cCapability='CAPABILITY', cRequirement='REQUIREMENT', cNecessity='NECESSITY', cWeight='WEIGHT',
  cCoworker='COWORKER', cMatch='MATCH', cWhy='WHY THIS POSITION IN THE ORDER', cWhyNot='WHY THEY WERE NOT CONSIDERED',
  mandatory='Mandatory', preferred='Preferred', mustHold='Must hold it', levelOrAbove='Level {n} or above',
  assignedPill='Assigned', fullBreakdown='Full breakdown',
  highPriority='High priority', normalPriority='Normal priority', estimated='{n} h estimated', due='Due {d}', language='Language: {l}',
  ownEyebrow='Ownership', ownTitle='Finished work keeps the name on it',
  ownBody='Every completed task stays attached to the person who did it, permanently. Six months from now you can still answer who worked on that machine, when, and why they were the one sent — without asking anyone to remember.',
  kpi1='Completed this quarter', kpi1h='Across five coworkers',
  kpi2='Assigned today', kpi2h='Both automatically',
  kpi3='Misdirected', kpi3h='Nobody worked outside their qualifications',
  kpi4='Admin time per task', kpi4h='Describe it once, then nothing',
  stateAssigned='Assigned today', stateCompleted='Completed',
  closeEyebrow='Why it matters', closeTitle='The point is not that a computer picks a name',
  closeBody='The point is that an unqualified person can never receive a task, and that months later you can still show exactly why a particular job went to a particular person. Distribution stops being someone’s morning and becomes a record.',
  p1t='Same inputs, same answer', p1b='No randomness anywhere. Run this distribution a hundred times and it picks the same person a hundred times, in the same order.',
  p2t='Or it refuses to choose', p2b='When two people are genuinely inseparable, a strict folder sends the decision to a human rather than guessing. Refusing is a legitimate outcome.',
  p3t='Work spreads out', p3b='Workload balance is a ranking factor, so the strongest person does not quietly absorb every job in the queue.',
  p4t='Overrides are allowed — and logged', p4b='An admin can assign past a failed requirement, but only by writing down why. That reason is kept next to their name.',
  foot1='Every score, rejection reason and ranking on this page is real output from the matching engine, generated by running these five profiles and these two tasks through it — not written by hand.',
  foot2='The people are fictional and the portraits are illustrations. Demonstration data for presentation purposes.',
 ),
 'da': dict(
  lang='da', title='Det rigtige navn på den', other='en', otherLabel='English', selfLabel='Dansk',
  badge='Opgavefordeling efter kompetencer',
  heroTitle='Opgaven lægges i en mappe. Det rigtige navn kommer ud.',
  heroBody='En fordelingsansvarlig lægger en opgave i en mappe og tænker ikke mere over den. Systemet holder den op mod, hvad hver enkelt på holdet rent faktisk kan — registrerede niveauer, certifikater og deres udløbsdatoer, tilgængelighed og arbejdsbyrde — sorterer alle ukvalificerede fra, rangerer dem, der er tilbage, og giver arbejdet videre med begrundelsen vedhæftet.',
  chip1='Ingen ukvalificeret kommer nogensinde i betragtning',
  chip2='Hver beslutning forklarer sig selv',
  chip3='Fuldført arbejde bliver knyttet til en person',
  pipeEyebrow='Hvad der sker med én opgave', pipeTitle='Fire trin, i denne rækkefølge, hver gang',
  pipeBody='Rækkefølgen er afgørende. Kvalifikationen afgøres, før rangeringen begynder, så ingen score kan overtale systemet til at vælge en, der ikke burde være der.',
  step='TRIN',
  s1t='Den ansvarlige udfylder opgaven', s1b='Hvad arbejdet er, hvor lang tid det bør tage, hvornår fristen er, og hvilke kompetencer det kræver. Det er den sidste beslutning, et menneske skal træffe.',
  s2t='Ukvalificerede sorteres fra', s2b='Manglende kompetence, for lavt niveau, udløbet certifikat, forkert sprog, orlov, ingen ledig kapacitet. Fejler man ét af dem, er man ude — der er ingen score i dette trin.',
  s3t='Resten bliver rangeret', s3b='Syv vægtede faktorer: hvor langt hver enkelt ligger over kravet, om en leder har godkendt det, erfaring, ledig kapacitet, fordeling af arbejdsbyrde, fristen og hvor godt rollen passer.',
  s4t='Én person får den — og det står i journalen', s4b='Tildelingen bærer sin egen begrundelse. Alle, der blev forbigået, står opført med præcis det krav, de ikke opfyldte.',
  teamEyebrow='Holdet', teamTitle='Fem personer, fem forskellige uddannelser',
  teamBody1='Det er dette, systemet læser. Ikke en jobtitel — en specifikation: hvad hver enkelt har læst, hvad de reelt er gode til og på hvilket niveau, hvilke certifikater de har, og hvornår de udløber, samt hver opgave, de har fuldført.',
  teamBody2a='En kompetence markeret med', teamBody2b='er godkendt af en leder. En, der kun er selvangivet, tæller stadig med, men rangerer under en verificeret.',
  hEducation='UDDANNELSE', hGoodAt='HVAD DE ER GODE TIL', hCompleted='ARBEJDE DE HAR FULDFØRT', thesisWord='Speciale:',
  d1Eyebrow='Beslutning ét — filteret gør arbejdet', d1Title='Et akut udkald på et anlæg under spænding',
  d1Body1='En pakkelinje udfalder gentagne gange. Anlægget er under spænding, så opgaven kræver en, der både kan finde en elektrisk fejl <em>og</em> har et gyldigt L-AUS-bevis. Den ansvarlige skriver det én gang og sender det til mappen.',
  d1Body2='Fire ud af fem sorteres fra — og af fire <em>forskellige</em> grunde. Læg især mærke til Freja.',
  d1NoteTitle='Det er her, det er værd at stoppe op.',
  d1NoteBody='Freja er elektriker. Hun har fejlfinding på niveau 4, verificeret, og holdets bedste score i kundeoverdragelse. Et menneske, der løb en navneliste igennem, ville have sendt hende. Hendes bevis udløb for enogtyve dage siden, så det ville systemet ikke — og det siger det på én linje i stedet for at lade hende møde op på et anlæg under spænding uden det.',
  d2Eyebrow='Beslutning to — rangeringen gør arbejdet', d2Title='En kvartalsrapport, samme fem personer',
  d2Body1='Nu får mappen noget helt andet: en rapport om driftssikkerhed, der kræver teknisk skrivning og helst dataanalyse. Fire er kvalificerede, så filteret træder tilbage, og rangeringen afgør det.',
  d2Body2='<strong>Og Freja er tilbage i spillet.</strong> Hendes udløbne bevis havde intet med at skrive en rapport at gøre, så det indgår slet ikke i beregningen. Systemet vurderer hver opgave ud fra dens egne krav — det bærer ikke nag fra den ene opgave til den næste.',
  d2NoteTitle='Jonas vinder på fortjeneste, ikke anciennitet.',
  d2NoteBody='Han er den nyeste på holdet og den, der har fået tildelt færrest opgaver. Han får denne, fordi han klarer begge kompetencer med god margin, begge er godkendt af en leder, og han har den letteste arbejdsbyrde — ikke fordi nogen kom i tanke om hans navn.',
  reqTitle='Hvad denne opgave kræver', shortTitle='Rangeret kandidatliste', blockTitle='Ikke taget i betragtning — og præcis hvorfor', blockTitle2='Ikke taget i betragtning',
  cCapability='KOMPETENCE', cRequirement='KRAV', cNecessity='NØDVENDIGHED', cWeight='VÆGT',
  cCoworker='MEDARBEJDER', cMatch='MATCH', cWhy='HVORFOR DENNE PLACERING', cWhyNot='HVORFOR DE IKKE KOM I BETRAGTNING',
  mandatory='Obligatorisk', preferred='Ønsket', mustHold='Skal haves', levelOrAbove='Niveau {n} eller derover',
  assignedPill='Tildelt', fullBreakdown='Fuld udspecificering',
  highPriority='Høj prioritet', normalPriority='Normal prioritet', estimated='{n} t estimeret', due='Frist {d}', language='Sprog: {l}',
  ownEyebrow='Ejerskab', ownTitle='Fuldført arbejde beholder navnet på sig',
  ownBody='Hver fuldført opgave forbliver permanent knyttet til den, der udførte den. Om et halvt år kan du stadig svare på, hvem der arbejdede på den maskine, hvornår, og hvorfor netop vedkommende blev sendt — uden at bede nogen om at huske det.',
  kpi1='Fuldført i dette kvartal', kpi1h='Fordelt på fem medarbejdere',
  kpi2='Tildelt i dag', kpi2h='Begge automatisk',
  kpi3='Fejlfordelt', kpi3h='Ingen har arbejdet uden for sine kvalifikationer',
  kpi4='Administrationstid pr. opgave', kpi4h='Beskriv den én gang, og så ikke mere',
  stateAssigned='Tildelt i dag', stateCompleted='Fuldført',
  closeEyebrow='Hvorfor det betyder noget', closeTitle='Pointen er ikke, at en computer vælger et navn',
  closeBody='Pointen er, at en ukvalificeret aldrig kan få en opgave, og at du måneder senere stadig kan vise præcis, hvorfor netop den opgave gik til netop den person. Fordeling holder op med at være nogens formiddag og bliver til dokumentation.',
  p1t='Samme input, samme svar', p1b='Ingen tilfældighed nogen steder. Kør denne fordeling hundrede gange, og den vælger den samme person hundrede gange, i samme rækkefølge.',
  p2t='Eller den nægter at vælge', p2b='Når to reelt ikke kan skelnes, sender en streng mappe beslutningen videre til et menneske frem for at gætte. At nægte er et gyldigt udfald.',
  p3t='Arbejdet spredes', p3b='Fordeling af arbejdsbyrde er en rangeringsfaktor, så den stærkeste ikke stille og roligt opsluger hele køen.',
  p4t='Overstyring er tilladt — og bliver logget', p4b='Den ansvarlige kan tildele på trods af et uopfyldt krav, men kun ved at skrive begrundelsen ned. Den begrundelse bliver stående ved siden af navnet.',
  foot1='Hver score, hver afvisningsgrund og hver rangering på denne side er reelt output fra matchningsmotoren, fremstillet ved at køre disse fem profiler og disse to opgaver igennem den — ikke skrevet i hånden.',
  foot2='Personerne er opdigtede, og portrætterne er illustrationer. Demonstrationsdata til brug ved fremlæggelse.',
 ),
}
