# -*- coding: utf-8 -*-
"""The five profiles, in both languages."""

PEOPLE = {
 'en': {
  'sofie': dict(name='Sofie Lindgren', role='Senior Electrical Technician · Field Service',
    edu='MSc Electrical Power Engineering', school='Danmarks Tekniske Universitet (DTU)',
    thesis='Arc-fault signatures in low-voltage distribution boards',
    blurb='Reads a fault from its transient signature before opening the panel. The one the team calls when a trip has no obvious cause.',
    caps=[('Electrical fault-finding',5,True,None),('Low-voltage work permit',5,True,'Valid to 30 Jun 2027'),
          ('High-voltage switching',4,True,None),('Customer handover',4,True,None),('Technical report writing',3,False,None)],
    hist=[('TSK-1908','Replace damaged distribution board, north site','12 Aug'),
          ('TSK-1876','Emergency isolation after water ingress, Hillerød','31 Jul'),
          ('TSK-1844','Thermographic survey, main switchroom','18 Jul')],
    load='2 open · 12 of 37 h'),
  'freja': dict(name='Freja Nilsen', role='Field Service Engineer · Field Service',
    edu='BEng Electrical Installation & Service', school='Københavns Erhvervsakademi (KEA)',
    thesis='Reducing handover defects through structured customer sign-off',
    blurb='Turns a finished repair into a signed, documented handover. Customers ask for her by name.',
    caps=[('Customer handover',5,True,None),('Electrical fault-finding',4,True,None),
          ('Technical report writing',4,False,None),('Low-voltage work permit',5,True,'LAPSED 5 Aug 2026')],
    hist=[('TSK-1921','Customer handover and acceptance test, Køge line 2','20 Aug'),
          ('TSK-1889','Service visit, packaging hall','5 Aug'),
          ('TSK-1857','Fault report, conveyor drive','22 Jul')],
    load='3 open · 18 of 37 h'),
  'mikkel': dict(name='Mikkel Dahl', role='Automation Engineer · Automation',
    edu='BEng Automation & Control Engineering', school='Aarhus Universitet',
    thesis='Safety-rated PLC architectures for collaborative robot cells',
    blurb='Builds the control logic that makes a machine safe to stand next to, and proves it on paper afterwards.',
    caps=[('PLC programming',5,True,None),('Safety systems',4,True,None),('Technical report writing',4,True,None),
          ('Data analysis',2,False,None),('Electrical fault-finding',2,False,None),('Low-voltage work permit',5,True,'Valid to 1 Mar 2027')],
    hist=[('TSK-1915','Commission palletiser cell, Vejle','17 Aug'),
          ('TSK-1902','Safety circuit proving after guard rebuild','9 Aug'),
          ('TSK-1868','PLC migration, line 4','28 Jul')],
    load='4 open · 22 of 37 h'),
  'jonas': dict(name='Jonas Berg', role='Reliability Data Engineer · Automation',
    edu='MSc Data Engineering', school='IT-Universitetet i København (ITU)',
    thesis='Predictive maintenance from vibration telemetry',
    blurb='Finds the failure three weeks before it happens, then writes it up so someone can act on it.',
    caps=[('Data analysis',5,True,None),('Technical report writing',5,True,None),('PLC programming',3,False,None)],
    hist=[('TSK-1912','Downtime analysis, Q2','15 Aug'),
          ('TSK-1881','Sensor data pipeline for bearing telemetry','2 Aug'),
          ('TSK-1839','Reliability baseline report, all sites','15 Jul')],
    load='1 open · 8 of 30 h'),
  'amira': dict(name='Amira Haddad', role='Senior Mechanical Technician · Workshop',
    edu='MSc Mechanical Engineering', school='Lunds Universitet',
    thesis='Fatigue life prediction in high-pressure hydraulic cylinders',
    blurb='Rebuilds what everyone else writes off. Knows exactly how many cycles a cylinder has left in it.',
    caps=[('Hydraulics',5,True,None),('MIG welding',4,True,None),('Forklift licence',5,True,'Valid to 1 Nov 2027'),
          ('Technical report writing',3,False,None)],
    hist=[('TSK-1898','Rebuild tipper ram assembly','7 Aug'),
          ('TSK-1866','Weld repair, boom section','26 Jul'),
          ('TSK-1831','Hydraulic press overhaul','11 Jul')],
    load='On leave · back 14 Sep'),
 },
 'da': {
  'sofie': dict(name='Sofie Lindgren', role='Erfaren eltekniker · Service',
    edu='Civilingeniør i elektrisk energiteknik', school='Danmarks Tekniske Universitet (DTU)',
    thesis='Lysbuefejls signatur i lavspændingstavler',
    blurb='Aflæser en fejl på dens transiente signatur, før tavlen overhovedet åbnes. Den, holdet ringer til, når et udfald ikke har nogen åbenlys årsag.',
    caps=[('Elektrisk fejlfinding',5,True,None),('L-AUS-bevis',5,True,'Gyldigt til 30. juni 2027'),
          ('Højspændingskobling',4,True,None),('Kundeoverdragelse',4,True,None),('Teknisk rapportskrivning',3,False,None)],
    hist=[('TSK-1908','Udskiftning af beskadiget eltavle, nordlige anlæg','12. aug.'),
          ('TSK-1876','Nødafbrydelse efter vandindtrængning, Hillerød','31. jul.'),
          ('TSK-1844','Termografisk gennemgang, hovedtavlerum','18. jul.')],
    load='2 åbne · 12 af 37 t'),
  'freja': dict(name='Freja Nilsen', role='Servicetekniker · Service',
    edu='Diplomingeniør i elinstallation og service', school='Københavns Erhvervsakademi (KEA)',
    thesis='Færre fejl ved overdragelse gennem struktureret kundegodkendelse',
    blurb='Forvandler en færdig reparation til en underskrevet, dokumenteret overdragelse. Kunderne beder om hende ved navn.',
    caps=[('Kundeoverdragelse',5,True,None),('Elektrisk fejlfinding',4,True,None),
          ('Teknisk rapportskrivning',4,False,None),('L-AUS-bevis',5,True,'UDLØBET 5. august 2026')],
    hist=[('TSK-1921','Kundeoverdragelse og afleveringsprøve, Køge linje 2','20. aug.'),
          ('TSK-1889','Servicebesøg, pakkehal','5. aug.'),
          ('TSK-1857','Fejlrapport, transportbånd','22. jul.')],
    load='3 åbne · 18 af 37 t'),
  'mikkel': dict(name='Mikkel Dahl', role='Automationsingeniør · Automation',
    edu='Diplomingeniør i automation og drift', school='Aarhus Universitet',
    thesis='Sikkerhedsgodkendte PLC-arkitekturer til samarbejdende robotceller',
    blurb='Bygger den styringslogik, der gør en maskine sikker at stå ved siden af — og dokumenterer det bagefter.',
    caps=[('PLC-programmering',5,True,None),('Sikkerhedssystemer',4,True,None),('Teknisk rapportskrivning',4,True,None),
          ('Dataanalyse',2,False,None),('Elektrisk fejlfinding',2,False,None),('L-AUS-bevis',5,True,'Gyldigt til 1. marts 2027')],
    hist=[('TSK-1915','Idriftsættelse af palleteringscelle, Vejle','17. aug.'),
          ('TSK-1902','Afprøvning af sikkerhedskreds efter ombygning','9. aug.'),
          ('TSK-1868','PLC-migrering, linje 4','28. jul.')],
    load='4 åbne · 22 af 37 t'),
  'jonas': dict(name='Jonas Berg', role='Dataingeniør, driftssikkerhed · Automation',
    edu='Cand.scient. i dataingeniørvidenskab', school='IT-Universitetet i København (ITU)',
    thesis='Forudsigende vedligehold ud fra vibrationsdata',
    blurb='Finder nedbruddet tre uger før det sker, og skriver det op, så nogen kan handle på det.',
    caps=[('Dataanalyse',5,True,None),('Teknisk rapportskrivning',5,True,None),('PLC-programmering',3,False,None)],
    hist=[('TSK-1912','Nedetidsanalyse, 2. kvartal','15. aug.'),
          ('TSK-1881','Datapipeline for lejeovervågning','2. aug.'),
          ('TSK-1839','Basisrapport om driftssikkerhed, alle anlæg','15. jul.')],
    load='1 åben · 8 af 30 t'),
  'amira': dict(name='Amira Haddad', role='Erfaren maskintekniker · Værksted',
    edu='Civilingeniør i maskinteknik', school='Lunds Universitet',
    thesis='Forudsigelse af udmattelseslevetid i højtrykshydraulikcylindre',
    blurb='Genopbygger det, alle andre afskriver. Ved præcis, hvor mange cyklusser en cylinder har tilbage.',
    caps=[('Hydraulik',5,True,None),('MIG-svejsning',4,True,None),('Truckcertifikat',5,True,'Gyldigt til 1. november 2027'),
          ('Teknisk rapportskrivning',3,False,None)],
    hist=[('TSK-1898','Renovering af tipcylinder','7. aug.'),
          ('TSK-1866','Svejsereparation, bomsektion','26. jul.'),
          ('TSK-1831','Hovedeftersyn af hydraulikpresse','11. jul.')],
    load='På orlov · tilbage 14. sep.'),
 },
}

ARCHIVE = {
 'en': [
  ('26 Aug','TSK-2041','Intermittent trip on the packing line feeder','sofie',True),
  ('26 Aug','TSK-2042','Quarterly reliability report — Aarhus site','jonas',True),
  ('20 Aug','TSK-1921','Customer handover and acceptance test, Køge line 2','freja',False),
  ('17 Aug','TSK-1915','Commission palletiser cell, Vejle','mikkel',False),
  ('15 Aug','TSK-1912','Downtime analysis, Q2','jonas',False),
  ('12 Aug','TSK-1908','Replace damaged distribution board, north site','sofie',False),
  ('9 Aug','TSK-1902','Safety circuit proving after guard rebuild','mikkel',False),
  ('7 Aug','TSK-1898','Rebuild tipper ram assembly','amira',False),
  ('5 Aug','TSK-1889','Service visit, packaging hall','freja',False),
  ('2 Aug','TSK-1881','Sensor data pipeline for bearing telemetry','jonas',False),
  ('31 Jul','TSK-1876','Emergency isolation after water ingress, Hillerød','sofie',False),
  ('28 Jul','TSK-1868','PLC migration, line 4','mikkel',False),
  ('26 Jul','TSK-1866','Weld repair, boom section','amira',False),
  ('22 Jul','TSK-1857','Fault report, conveyor drive','freja',False),
  ('18 Jul','TSK-1844','Thermographic survey, main switchroom','sofie',False),
  ('15 Jul','TSK-1839','Reliability baseline report, all sites','jonas',False),
  ('11 Jul','TSK-1831','Hydraulic press overhaul','amira',False),
 ],
 'da': [
  ('26. aug.','TSK-2041','Uregelmæssigt udfald på pakkelinjens indfødning','sofie',True),
  ('26. aug.','TSK-2042','Kvartalsrapport om driftssikkerhed — Aarhus','jonas',True),
  ('20. aug.','TSK-1921','Kundeoverdragelse og afleveringsprøve, Køge linje 2','freja',False),
  ('17. aug.','TSK-1915','Idriftsættelse af palleteringscelle, Vejle','mikkel',False),
  ('15. aug.','TSK-1912','Nedetidsanalyse, 2. kvartal','jonas',False),
  ('12. aug.','TSK-1908','Udskiftning af beskadiget eltavle, nordlige anlæg','sofie',False),
  ('9. aug.','TSK-1902','Afprøvning af sikkerhedskreds efter ombygning','mikkel',False),
  ('7. aug.','TSK-1898','Renovering af tipcylinder','amira',False),
  ('5. aug.','TSK-1889','Servicebesøg, pakkehal','freja',False),
  ('2. aug.','TSK-1881','Datapipeline for lejeovervågning','jonas',False),
  ('31. jul.','TSK-1876','Nødafbrydelse efter vandindtrængning, Hillerød','sofie',False),
  ('28. jul.','TSK-1868','PLC-migrering, linje 4','mikkel',False),
  ('26. jul.','TSK-1866','Svejsereparation, bomsektion','amira',False),
  ('22. jul.','TSK-1857','Fejlrapport, transportbånd','freja',False),
  ('18. jul.','TSK-1844','Termografisk gennemgang, hovedtavlerum','sofie',False),
  ('15. jul.','TSK-1839','Basisrapport om driftssikkerhed, alle anlæg','jonas',False),
  ('11. jul.','TSK-1831','Hovedeftersyn af hydraulikpresse','amira',False),
 ],
}
